version: '3'
services:
    web:
        build: .
        image: forum-wechat
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./app:/home/forum-wechat/app
            - ./instance:/home/forum-wechat/instance
            - ./migrations:/home/forum-wechat/migrations
        env_file:
            - ./.docker-env/web
        depends_on:
            - mysql
        container_name: forum-wechat
    caddy:
        image: kaiwk/caddy
        restart: always
        volumes:
            - ./:/root/forum-wechat/
            - ./docker/conf/caddy/Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - web
        ports:
            - 80:80
            - 443:443
        container_name: forum-webserver
    mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306
        env_file:
            - ./.docker-env/mysql
        command: ['mysqld', '--max-connections=200',
                            '--character-set-server=utf8mb4',
                            '--collation-server=utf8mb4_unicode_ci']
        container_name: forum-mysql
    webhook:
        image: kaiwk/webhook-github
        restart: always
        volumes:
            - ./:/project-repo
        ports:
            - 8000:8000
        env_file:
            - ./.docker-env/webhook-github
        container_name: webhook-github
