"""empty message

Revision ID: a9a574745f9c
Revises: 5a20064c47d9
Create Date: 2018-12-15 00:34:15.012085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a574745f9c'
down_revision = '5a20064c47d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('anonymous', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('closed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('self_intro', sa.String(length=200), nullable=True))
    op.alter_column('user', 'open_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'open_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.drop_column('user', 'self_intro')
    op.drop_column('question', 'closed')
    op.drop_column('answer', 'anonymous')
    # ### end Alembic commands ###
